# Generated by Django 5.0.2 on 2025-12-04 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_movil_escolar_api', '0004_maestros_edad_alter_alumnos_curp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventoAcademico',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('tipo', models.CharField(max_length=100)),
                ('fecha', models.DateField()),
                ('hora_inicio', models.TimeField()),
                ('hora_fin', models.TimeField()),
                ('lugar', models.CharField(max_length=200)),
                ('publico', models.JSONField(default=list)),
                ('programa', models.CharField(blank=True, max_length=200, null=True)),
                ('responsable', models.IntegerField()),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('cupo', models.IntegerField()),
            ],
        ),
    ]
